name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # generate snake svg image
      - name: generate snake
        uses: Platane/snk/svg-only@v2
        with:
          outputs: snake/snake.svg
          github_user_name: ${{ github.repository_owner }}
      # generate summary svg image
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      # merge generated files
      - name: merge files
        run: mkdir output & mv snake output && mv profile-3d-contrib output
      # push files to output branch
      - name: push builds to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
